version: '3.8'

services:
  db:
    image: postgres:15
    container_name: home_postgres
    restart: always
    # env_file:
    #   - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
    volumes:
      - home_postgres_data:/var/lib/postgresql/data
      - db_backup:/backup
    # ports:
    #   - "5434:5432"
    expose:
      - "5432"

  redis:
    image: redis:alpine
    container_name: home_redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      retries: 5
    volumes:
      - home_redis_data:/data
    ports:
      - "6379:6379"  # Keep the default port


  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    # env_file:
    #   - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis:6379/0
    ports:
      - "4002:4002"
    volumes:
      - static_vmsh:/vmsh/static


volumes:
  home_postgres_data:
  home_redis_data:
  static_vmsh:
  db_backup:


  # volumes:
  # home_postgres_data:
  #   external: true
  # home_redis_data:
  #   external: true
  # static_vmsh:
  # db_backup:  # <--- Add this line if it's a volume
