# Generated by Django 5.1.7 on 2025-03-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0006_alter_appointment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('progress', 'In Progress'), ('completed', 'Completed'), ('call', 'Call'), ('cancel', 'Cancel')], default='pending', max_length=20),
        ),
    ]
