# Generated by Django 5.1.5 on 2025-02-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pass_key',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
