# Generated by Django 5.1.5 on 2025-03-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_alter_customuser_pass_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='roles',
        ),
    ]
