# Generated by Django 5.1.5 on 2025-03-18 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0003_remove_customuser_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gm',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'GM'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
