# Generated by Django 5.1.5 on 2025-03-12 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_screenactivity_live_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenactivity',
            name='password',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
